#!/bin/bash
# Visualizar estrutura completa do projeto

clear
echo ""
echo "╔════════════════════════════════════════════════════════════╗"
echo "║    🧔 BARBEARIA SENSE - ESTRUTURA DO PROJETO              ║"
echo "║         Sistema de Agendamento Online                     ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""

echo "📁 PASTA RAIZ: sense_barber"
echo "├── 📄 README.md                   ← LEIA PRIMEIRO!"
echo "├── 📄 INSTALACAO.md               ← Guia passo a passo"
echo "├── 📄 FAQ.md                      ← Perguntas frequentes"
echo "├── 🚀 start.bat                   ← Quick start (Windows)"
echo "├── 🚀 start.sh                    ← Quick start (Mac/Linux)"
echo ""

echo "├── 📂 FRONTEND (Interface Web)"
echo "│   ├── 📄 index.html              ← Página principal"
echo "│   ├── 📄 README.md               ← Documentação frontend"
echo "│   ├── 📄 package.json            ← Dependências npm"
echo "│   ├── 📁 css/"
echo "│   │   ├── 📄 style.css           ← Estilos principais"
echo "│   │   └── 📄 responsive.css      ← Estilos mobile"
echo "│   ├── 📁 js/"
echo "│   │   ├── 📄 main.js             ← Funções principais"
echo "│   │   └── 📄 agendamento.js      ← Lógica de agendamento"
echo "│   └── 📁 assets/"
echo "│       ├── 📄 README.md           ← Guia de imagens"
echo "│       ├── 🖼️  logo.png           ← Seu logotipo (FORNECIDO)"
echo "│       ├── 📸 barbeiro1.jpg       ← Fotos dos barbeiros"
echo "│       ├── 📸 barbeiro2.jpg       │  (adicione suas)"
echo "│       └── 📸 barbeiro3.jpg       ←"
echo ""

echo "└── 📂 BACKEND (API & Banco de Dados)"
echo "    ├── 📄 server.js               ← Servidor principal"
echo "    ├── 📄 package.json            ← Dependências npm"
echo "    ├── 📄 .env                    ← Configuração"
echo "    ├── 📄 .env.example            ← Template .env"
echo "    ├── 📄 .gitignore              ← Git ignorar"
echo "    ├── 📄 README.md               ← Documentação API"
echo "    ├── 📁 database/"
echo "    │   ├── 📄 database.js         ← Gerenciador SQLite"
echo "    │   └── 📊 barbearia_sense.db  ← Banco de dados"
echo "    └── 📁 routes/"
echo "        ├── 📄 servicos.js         ← CRUD de serviços"
echo "        ├── 📄 barbeiros.js        ← CRUD de barbeiros"
echo "        ├── 📄 agendamentos.js     ← Sistema agendamentos"
echo "        └── 📄 email.js            ← Envio de emails"
echo ""

echo "════════════════════════════════════════════════════════════"
echo ""

echo "🎯 ARQUIVO QUE VOCÊ DEVE ABRIR:"
echo "   → frontend/index.html (ou http://localhost:5500)"
echo ""

echo "⚙️ COMO EXECUTAR:"
echo "   1. Abra terminal na pasta 'sense_barber'"
echo "   2. Execute: npm install (na pasta backend)"
echo "   3. Execute: npm start (na pasta backend)"
echo "   4. Abra frontend/index.html com Live Server"
echo ""

echo "📖 DOCUMENTAÇÃO:"
echo "   → README.md            - Visão geral do projeto"
echo "   → INSTALACAO.md        - Passo a passo de instalação"
echo "   → FAQ.md               - Perguntas frequentes"
echo "   → backend/README.md    - API e endpoints"
echo "   → frontend/README.md   - Frontend e customização"
echo ""

echo "🎨 O LOGOTIPO JÁ ESTÁ PRONTO!"
echo "   Local: frontend/assets/logo.png"
echo "   Design: Tesoura, barba, pincél com cores dourado/preto/branco"
echo "   Será automaticamente usado em todo o site"
echo ""

echo "✨ FUNCIONALIDADES:"
echo "   ✅ Sistema completo de agendamento"
echo "   ✅ Design moderno e responsivo"
echo "   ✅ API REST documentada"
echo "   ✅ Banco de dados SQLite"
echo "   ✅ Email de confirmação"
echo "   ✅ Dados de exemplo pré-carregados"
echo ""

echo "════════════════════════════════════════════════════════════"
echo ""
echo "🚀 PRÓXIMOS PASSOS:"
echo ""
echo "1. LER: cat README.md"
echo "2. INSTALAR: cd backend && npm install"
echo "3. INICIAR: npm start"
echo "4. ABRIR: frontend/index.html com Live Server"
echo ""
echo "════════════════════════════════════════════════════════════"
echo ""
echo "Desenvolvido para Barbearia Sense 🧔✨"
echo ""
